# Generated by Django 5.2.7 on 2025-10-26 18:39

from django.db import migrations


def create_categories(apps, schema_editor):
    """Create initial blog categories"""
    BlogCategory = apps.get_model('blog', 'BlogCategory')
    categories = [
        {'name': 'Mental Health', 'description': 'Posts about mental health and wellness'},
        {'name': 'Heart Disease', 'description': 'Posts about cardiovascular health'},
        {'name': 'COVID-19', 'description': 'Posts about COVID-19 and pandemic updates'},
        {'name': 'Immunization', 'description': 'Posts about vaccines and immunization'},
    ]
    for cat in categories:
        BlogCategory.objects.get_or_create(name=cat['name'], defaults={'description': cat['description']})


def delete_categories(apps, schema_editor):
    """Reverse operation - delete categories"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_categories, delete_categories),
    ]
